version: "3.9"

services:
  database:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=journal-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
